### ISSUE TITLE
Only worked once!

### ISSUE THREAD

**Issue by vexillia** [keithfancher/todo-indicator#7]
Installed as instructed.  Launched OK but closed after a closed my terminal session.  AFter that it wouldn't open.

Running xubuntu 22.04.

**Comment by keithfancher** [comment]
Hello, and thanks for filing this!

> Launched OK but closed after a closed my terminal session.

This is actually "normal" behavior for starting applications from the terminal -- if you close the terminal, by default, it'll kill processes started by that terminal. There are a handful of ways to deal with this:

**1.** You can use `& disown` when you start an application from the terminal if you know you want to close that terminal session (and leave the app running), e.g.:
```sh
$ todo-indicator ~/todo.txt & disown
```
Now you can close your terminal and the indicator will stick around until you explicitly exit it.

**2.** You can also launch it with the "Run a command" dialog, rather than the terminal. This is usually Alt+F2. (I'm *pretty* sure it's the same in Xubuntu, though I haven't used Xubuntu in quite some time!)

**3.** A more long-term solution might be to stick the `todo-indicator` call in your "Startup Applications", assuming you want it to automatically start. (Depending on your `$PATH` setup, you might need to use the full path to `todo-indicator` in this or the above "Run a command" case.)

> After that it wouldn't open.

This part's strange. If the application is closed, it should start again no problem. You might try checking your "System monitor" to see if it's lingering, and manually kill it. Alternatively, if you're comfortable with the command-line approach, something like:

```sh
$ ps x | grep todo-indicator
 207255 pts/1    SNl    0:00 /usr/local/bin/python ./todo-indicator sample-todo.txt
# And now you can kill the process with the above PID ^
$ kill 207255
```

Let me know if you run into issues! And thanks again for filing -- I think the docs could definitely be more clear about this. Will update!

**Comment by vexillia** [comment]
Thanks. Tried again and got this:

`(todo-indicator:592082): dbind-WARNING **: 09:10:36.165: Couldn't connect to accessibility bus: Failed to connect to socket /root/.cache/at-spi/bus_0.0: Permission denied`

**Comment by vexillia** [comment]
Blizted everything now working.

**Comment by keithfancher** [comment]
Awesome! Glad to hear it :tada:
